/**
 * E2B sandbox integration via Python wrapper subprocess.
 *
 * Architecture:
 *   Java code (this class)
 *     -> ProcessBuilder spawns: python3 e2b_runner.py <code-file> <output-png>
 *     -> Python wrapper uses official e2b-code-interpreter SDK
 *     -> SDK creates sandbox, runs code, returns PNG
 *     -> Python writes PNG to output file
 *     -> Java reads PNG bytes, returns to caller
 *
 * Why subprocess: E2B's official SDK is Python/Node only. Direct HTTP integration
 * from Java is fragile (see E2BSandboxClientHttpRaw.java for the original attempt).
 * Delegating to a small Python wrapper is the production-clean pattern.
 *
 * Required setup:
 *   pip install e2b-code-interpreter
 *   E2B_API_KEY env var must be set in the JVM's environment
 */
package com.sandboxlab.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.TimeUnit;

@Component
public class E2BSandboxClient {

    private static final Logger log = LoggerFactory.getLogger(E2BSandboxClient.class);

    private final String pythonExecutable;
    private final String runnerScriptPath;
    private final String apiKey;
    private final long timeoutSeconds;

    public E2BSandboxClient(
            @Value("${e2b.python-executable:python3}") String pythonExecutable,
            @Value("${e2b.runner-script:e2b_sandbox_client.py}") String runnerScriptPath,
            @Value("${e2b.api.key}") String apiKey,
            @Value("${e2b.subprocess-timeout-seconds:120}") long timeoutSeconds) {
        this.pythonExecutable = pythonExecutable;
        this.runnerScriptPath = runnerScriptPath;
        this.apiKey = apiKey;
        this.timeoutSeconds = timeoutSeconds;
        log.info("E2BSandboxClient initialized — build marker: PYTHON_WRAPPER_v3, runner='{}', timeout={}s @ {}",
                runnerScriptPath, timeoutSeconds, java.time.Instant.now());
    }

    /**
     * Runs Python code in an E2B sandbox and returns the resulting chart.png.
     *
     * @param pythonCode the Python code to execute (typically generated by an LLM)
     * @return PNG bytes of the chart created by the code
     * @throws RuntimeException if the subprocess fails, times out, or no chart is produced
     */
    public byte[] executePythonAndGetChart(String pythonCode) {
        Path codeFile = null;
        Path outputPng = null;
        try {
            // 1. Write the AI-generated Python code to a temp file
            codeFile = Files.createTempFile("e2b-code-", ".py");
            Files.writeString(codeFile, pythonCode);

            // 2. Prepare output PNG path (file does not exist yet; runner writes it)
            outputPng = Files.createTempFile("e2b-chart-", ".png");

            log.info(box("OUT → subprocess")
                + lbl("Code length", pythonCode.length() + " chars")
                + lbl("Code file",   codeFile)
                + lbl("Output file", outputPng)
                + lbl("Command",     pythonExecutable + " " + runnerScriptPath
                                     + " " + codeFile + " " + outputPng));

            // 3. Build subprocess: python3 e2b_sandbox_client.py <code> <output>
            ProcessBuilder pb = new ProcessBuilder(
                    pythonExecutable,
                    runnerScriptPath,
                    codeFile.toString(),
                    outputPng.toString()
            );
            // Pass E2B_API_KEY into the subprocess's environment
            pb.environment().put("E2B_API_KEY", apiKey);
            // Capture stdout and stderr separately so they can be logged individually

            long subprocStart = System.currentTimeMillis();
            Process proc = pb.start();

            // Drain stdout line by line in a background thread — Python's "[e2b_runner] ..."
            // prints flow into Java logs while the subprocess runs, sharing the MDC transactionId.
            StringBuilder stdoutCapture = new StringBuilder();
            Thread stdoutReader = new Thread(() -> {
                try (var reader = new BufferedReader(new InputStreamReader(proc.getInputStream(), StandardCharsets.UTF_8))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        log.info("[subprocess stdout] {}", line);
                        stdoutCapture.append(line).append("\n");
                    }
                } catch (Exception ignored) {}
            });

            // Drain stderr line by line — Python tracebacks and warnings land here
            StringBuilder stderrCapture = new StringBuilder();
            Thread stderrReader = new Thread(() -> {
                try (var reader = new BufferedReader(new InputStreamReader(proc.getErrorStream(), StandardCharsets.UTF_8))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        log.warn("[subprocess stderr] {}", line);
                        stderrCapture.append(line).append("\n");
                    }
                } catch (Exception ignored) {}
            });

            stdoutReader.start();
            stderrReader.start();

            // 4. Wait for completion with timeout
            boolean finished = proc.waitFor(timeoutSeconds, TimeUnit.SECONDS);
            if (!finished) {
                proc.destroyForcibly();
                stdoutReader.interrupt();
                stderrReader.interrupt();
                throw new RuntimeException("E2B runner timed out after " + timeoutSeconds + "s");
            }

            stdoutReader.join(5000);
            stderrReader.join(5000);

            int exitCode = proc.exitValue();
            long subprocDuration = System.currentTimeMillis() - subprocStart;
            log.info(box("IN ← subprocess")
                + lbl("Exit code",  exitCode)
                + lbl("Stdout",     stdoutCapture.length() + " chars")
                + lbl("Stderr",     stderrCapture.length() + " chars")
                + lbl("Duration",   subprocDuration + "ms"));

            if (exitCode != 0) {
                throw new RuntimeException(
                    "E2B runner failed (exit=" + exitCode + ")\n" +
                    "stdout: " + stdoutCapture +
                    "stderr: " + stderrCapture);
            }

            // 5. Read the PNG bytes from the output file
            byte[] pngBytes = Files.readAllBytes(outputPng);
            if (pngBytes.length == 0) {
                throw new RuntimeException("E2B runner reported success but output PNG is empty");
            }
            return pngBytes;

        } catch (RuntimeException e) {
            throw e;
        } catch (Exception e) {
            throw new RuntimeException("Failed to run E2B sandbox subprocess", e);
        } finally {
            // Cleanup temp files (best effort)
            try { if (codeFile  != null) Files.deleteIfExists(codeFile);  } catch (Exception ignored) {}
            try { if (outputPng != null) Files.deleteIfExists(outputPng); } catch (Exception ignored) {}
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    //  Log formatting helpers
    // ─────────────────────────────────────────────────────────────────────────

    private static final String BOX_H = "═".repeat(76);

    private static String box(String title) {
        return "\n╔" + BOX_H + "╗\n║  " + String.format("%-74s", title) + "║\n╚" + BOX_H + "╝";
    }

    private static String lbl(String label, Object value) {
        return "\n   " + String.format("%-11s", label) + " : " + value;
    }
}
